// Mocks generated by Mockito 5.4.5 from annotations
// in dicoding_flutter_restaurant_app/test/mock/mock_restaurant_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dicoding_flutter_restaurant_app/model/restaurant_review.dart'
    as _i5;
import 'package:dicoding_flutter_restaurant_app/service/restaurant_api.dart'
    as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestaurantAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantAPI extends _i1.Mock implements _i3.RestaurantAPI {
  MockRestaurantAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeDio_0(this, Invocation.getter(#api)),
          )
          as _i2.Dio);

  @override
  set api(_i2.Dio? _api) => super.noSuchMethod(
    Invocation.setter(#api, _api),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.Response<Map<dynamic, dynamic>>> getRestaurantList() =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantList, []),
            returnValue: _i4.Future<_i2.Response<Map<dynamic, dynamic>>>.value(
              _FakeResponse_1<Map<dynamic, dynamic>>(
                this,
                Invocation.method(#getRestaurantList, []),
              ),
            ),
          )
          as _i4.Future<_i2.Response<Map<dynamic, dynamic>>>);

  @override
  _i4.Future<_i2.Response<Map<dynamic, dynamic>>> getRestaurantDetail({
    required String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantDetail, [], {#id: id}),
            returnValue: _i4.Future<_i2.Response<Map<dynamic, dynamic>>>.value(
              _FakeResponse_1<Map<dynamic, dynamic>>(
                this,
                Invocation.method(#getRestaurantDetail, [], {#id: id}),
              ),
            ),
          )
          as _i4.Future<_i2.Response<Map<dynamic, dynamic>>>);

  @override
  _i4.Future<_i2.Response<Map<dynamic, dynamic>>> getSearchRestaurant({
    required String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchRestaurant, [], {#search: search}),
            returnValue: _i4.Future<_i2.Response<Map<dynamic, dynamic>>>.value(
              _FakeResponse_1<Map<dynamic, dynamic>>(
                this,
                Invocation.method(#getSearchRestaurant, [], {#search: search}),
              ),
            ),
          )
          as _i4.Future<_i2.Response<Map<dynamic, dynamic>>>);

  @override
  _i4.Future<_i2.Response<Map<dynamic, dynamic>>> addReviewRestaurant({
    required _i5.ReviewData? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addReviewRestaurant, [], {#data: data}),
            returnValue: _i4.Future<_i2.Response<Map<dynamic, dynamic>>>.value(
              _FakeResponse_1<Map<dynamic, dynamic>>(
                this,
                Invocation.method(#addReviewRestaurant, [], {#data: data}),
              ),
            ),
          )
          as _i4.Future<_i2.Response<Map<dynamic, dynamic>>>);
}
